p8105_hw2_yl5829
================
2024-10-01

## R Markdown

## Problem 1

``` r
#load the data in relative path
nyc <- read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c(".", "NA", ""))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(nyc)
```

    ## # A tibble: 6 × 32
    ##   Division Line     `Station Name` `Station Latitude` `Station Longitude` Route1
    ##   <chr>    <chr>    <chr>                       <dbl>               <dbl> <chr> 
    ## 1 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 2 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 3 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 4 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 5 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 6 BMT      4 Avenue 45th St                      40.6               -74.0 R     
    ## # ℹ 26 more variables: Route2 <chr>, Route3 <chr>, Route4 <chr>, Route5 <chr>,
    ## #   Route6 <chr>, Route7 <chr>, Route8 <dbl>, Route9 <dbl>, Route10 <dbl>,
    ## #   Route11 <dbl>, `Entrance Type` <chr>, Entry <chr>, `Exit Only` <chr>,
    ## #   Vending <chr>, Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>,
    ## #   `ADA Notes` <chr>, `Free Crossover` <lgl>, `North South Street` <chr>,
    ## #   `East West Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>,
    ## #   `Entrance Longitude` <dbl>, `Station Location` <chr>, …

``` r
#clean the data
nyc_clean <- nyc %>%
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, 
         route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, 
         entry, vending, entrance_type, ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

#look at the cleaned data
head(nyc_clean)
```

    ## # A tibble: 6 × 19
    ##   line     station_name station_latitude station_longitude route1 route2 route3
    ##   <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ## 1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ## 2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ## 3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

``` r
#check for column names
colnames(nyc)
```

    ##  [1] "Division"           "Line"               "Station Name"      
    ##  [4] "Station Latitude"   "Station Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance Type"      "Entry"             
    ## [19] "Exit Only"          "Vending"            "Staffing"          
    ## [22] "Staff Hours"        "ADA"                "ADA Notes"         
    ## [25] "Free Crossover"     "North South Street" "East West Street"  
    ## [28] "Corner"             "Entrance Latitude"  "Entrance Longitude"
    ## [31] "Station Location"   "Entrance Location"

``` r
#check for number of column
ncol(nyc)
```

    ## [1] 32

``` r
#check for dimension of cleaned data
dim(nyc_clean)
```

    ## [1] 1868   19

The dataset contains 32 variables and it mainly focuses on the subway
entrances and exits in the NYC transit system. The variables included
are line name, station name, geographic information (latitude and
longitude), various routes served by the station (up to 11 routes),
entry type, vending machine availability, some street, entrance type and
geographic information (latitude, longitude, and location), and ADA
compliance. After loading the data I use janitor::clean_names() function
to convert all the variable to lower case and replaced spaces with
underscores to better performe next step. I next select relevant
variables and transformed the entry column, which initially contained
“YES” and “NO” values, into a logical variable (TRUE for “YES” and FALSE
for “NO”). I also handled the missing values by specify any missing
value to be NA in the data. After clean there are 1868 rows and 19
columns in total. The data is tidy as each variable is stored in its own
column, each observation is in its own row, and the dataset is organized
for further analysis.

``` r
#the number of distinct stations
distinct_stations <- nyc_clean %>%
  distinct(station_name, line) %>%
  nrow()

#see the output
distinct_stations
```

    ## [1] 465

There are 465 distinct stations.

``` r
#the number of ADA compliant stations
ada_compliant <- nyc_clean %>%
  filter(ada == "TRUE") %>%
  distinct(station_name, line) %>%
  nrow()

#see the output
ada_compliant
```

    ## [1] 84

There are 84 ADA compliant.

``` r
#proportion of station entrances / exits without vending allow entrance
proportion <- nyc_clean %>%
  filter(vending == "NO" & entry == TRUE) %>%
  nrow() / nrow(nyc_clean)

# Output the proportion
proportion
```

    ## [1] 0.0369379

There is 0.0369 station entrances / exits without vending allow entrance

``` r
#convert all route columns to character type
nyc_clean <- nyc_clean %>%
  mutate(across(starts_with("route"), as.character))

#reshape the data
nyc_routes <- nyc_clean %>%
  pivot_longer(cols = starts_with("route"), names_to = "route_number", values_to = "route_name") %>%
  filter(!is.na(route_name))

#look at the reshaped data
head(nyc_routes)
```

    ## # A tibble: 6 × 10
    ##   line     station_name station_latitude station_longitude entry vending
    ##   <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ## 1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <chr>,
    ## #   route_name <chr>

``` r
#count distinct stations that serve the A train
a_train <- nyc_routes %>%
  filter(route_name == "A") %>%
  distinct(station_name, line) %>%
  nrow()

#number of distinct stations that serve the A train
a_train
```

    ## [1] 60

``` r
#count ADA compliant stations that serve the A train
a_ada <- nyc_routes %>%
  filter(route_name == "A", ada == TRUE) %>%
  distinct(station_name, line) %>%
  nrow()

#number of ADA compliant stations that serve the A train
a_ada
```

    ## [1] 17

There are 60 distinct stations serve the A train and of them 17 are ADA
compliant

## Problem 2

``` r
#load the mr trash wheel data in relative path
mr_wheel <- read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", na = c(".", "NA", ""))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
head(mr_wheel)
```

    ## # A tibble: 6 × 16
    ##   Dumpster Month Year  Date                `Weight (tons)`
    ##      <dbl> <chr> <chr> <dttm>                        <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00            4.31
    ## 2        2 May   2014  2014-05-16 00:00:00            2.74
    ## 3        3 May   2014  2014-05-16 00:00:00            3.45
    ## 4        4 May   2014  2014-05-17 00:00:00            3.1 
    ## 5        5 May   2014  2014-05-17 00:00:00            4.06
    ## 6        6 May   2014  2014-05-20 00:00:00            2.71
    ## # ℹ 11 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>, ...15 <lgl>, ...16 <lgl>

``` r
mr_wheel_clean <- mr_wheel %>%
  #make more reasonable names
  rename(
    dumpster = `Dumpster`,
    month = `Month`,  
    year = `Year`,    
    date = `Date`,
    weight_tons = `Weight (tons)`,
    volume_cubic_yards = `Volume (cubic yards)`,
    plastic_bottles = `Plastic Bottles`,
    polystyrene = `Polystyrene`,
    cigarette_butts = `Cigarette Butts`,
    glass_bottles = `Glass Bottles`,
    sports_balls = `Sports Balls`,
    homes_powered = `Homes Powered*`
  ) %>%
  mutate(year = as.character(year))%>%
  #remove rows that don't contain dumpster-specific data
  filter(!is.na(dumpster)) %>%
  #round the number of sports balls to the nearest integer and convert to integer
  mutate(sports_balls = as.integer(round(sports_balls, 0)))

#look at the cleaned data
head(mr_wheel_clean)
```

    ## # A tibble: 6 × 16
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## 6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ## # ℹ 10 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, ...15 <lgl>,
    ## #   ...16 <lgl>

``` r
#professor Trash Wheel data
prof_wheel <- read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel")

head(prof_wheel)
```

    ## # A tibble: 6 × 13
    ##   Dumpster Month     Year Date                `Weight (tons)`
    ##      <dbl> <chr>    <dbl> <dttm>                        <dbl>
    ## 1        1 January   2017 2017-01-02 00:00:00            1.79
    ## 2        2 January   2017 2017-01-30 00:00:00            1.58
    ## 3        3 February  2017 2017-02-26 00:00:00            2.32
    ## 4        4 February  2017 2017-02-26 00:00:00            3.72
    ## 5        5 February  2017 2017-02-28 00:00:00            1.45
    ## 6        6 March     2017 2017-03-30 00:00:00            1.71
    ## # ℹ 8 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
#clean Professor Trash Wheel data
prof_wheel_clean <- prof_wheel %>%
  rename(
    dumpster = `Dumpster`,
    month = `Month`,
    year = `Year`,
    date = `Date`,
    weight_tons = `Weight (tons)`,
    volume_cubic_yards = `Volume (cubic yards)`,
    plastic_bottles = `Plastic Bottles`,
    polystyrene = `Polystyrene`,
    cigarette_butts = `Cigarette Butts`,
    glass_bottles = `Glass Bottles`,
    plastic_bags = `Plastic Bags`,
    wrappers = `Wrappers`,
    homes_powered = `Homes Powered*`
  ) %>%
  mutate(year = as.character(year)) %>%
  filter(!is.na(dumpster))

head(prof_wheel_clean)
```

    ## # A tibble: 6 × 13
    ##   dumpster month    year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ## 2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ## 3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ## 4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ## 5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ## 6        6 March    2017  2017-03-30 00:00:00        1.71                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
#add a new column to identify the data source
prof_wheel_clean <- prof_wheel_clean %>%
  mutate(source = "Professor Trash Wheel")
prof_wheel_clean
```

    ## # A tibble: 119 × 14
    ##    dumpster month    year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ##  2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ##  3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ##  4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ##  5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ##  6        6 March    2017  2017-03-30 00:00:00        1.71                 15
    ##  7        7 April    2017  2017-04-01 00:00:00        1.82                 15
    ##  8        8 April    2017  2017-04-20 00:00:00        2.37                 15
    ##  9        9 May      2017  2017-05-10 00:00:00        2.64                 15
    ## 10       10 May      2017  2017-05-26 00:00:00        2.78                 15
    ## # ℹ 109 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, source <chr>

``` r
#Gwynnda Trash Wheel data
gwynnda_wheel <- read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel")
head(gwynnda_wheel)
```

    ## # A tibble: 6 × 12
    ##   Dumpster Month   Year Date                `Weight (tons)`
    ##      <dbl> <chr>  <dbl> <dttm>                        <dbl>
    ## 1        1 July    2021 2021-07-03 00:00:00            0.93
    ## 2        2 July    2021 2021-07-07 00:00:00            2.26
    ## 3        3 July    2021 2021-07-07 00:00:00            1.62
    ## 4        4 July    2021 2021-07-16 00:00:00            1.76
    ## 5        5 July    2021 2021-07-30 00:00:00            1.53
    ## 6        6 August  2021 2021-08-11 00:00:00            2.06
    ## # ℹ 7 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
#clean Gwynnda Trash Wheel data
gwynnda_wheel_clean <- gwynnda_wheel %>%
    rename(
    dumpster = `Dumpster`,
    month = `Month`,
    year = `Year`,
    date = `Date`,
    weight_tons = `Weight (tons)`,
    volume_cubic_yards = `Volume (cubic yards)`,
    plastic_bottles = `Plastic Bottles`,
    polystyrene = `Polystyrene`,
    cigarette_butts = `Cigarette Butts`,
    plastic_bags = `Plastic Bags`,
    wrappers = `Wrappers`,
    homes_powered = `Homes Powered*`
  ) %>%
  mutate(year = as.character(year))%>%
  #remove rows that don't contain dumpster-specific data
  filter(!is.na(dumpster))

#loot at the cleaned data
head(gwynnda_wheel_clean)
```

    ## # A tibble: 6 × 12
    ##   dumpster month  year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>  <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 July   2021  2021-07-03 00:00:00        0.93                 15
    ## 2        2 July   2021  2021-07-07 00:00:00        2.26                 15
    ## 3        3 July   2021  2021-07-07 00:00:00        1.62                 15
    ## 4        4 July   2021  2021-07-16 00:00:00        1.76                 15
    ## 5        5 July   2021  2021-07-30 00:00:00        1.53                 15
    ## 6        6 August 2021  2021-08-11 00:00:00        2.06                 15
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

``` r
#add a new column to identify the data source (Gwynnda Trash Wheel)
gwynnda_wheel_clean <- gwynnda_wheel_clean %>% mutate(source = "Gwynnda Trash Wheel")
head(gwynnda_wheel_clean)
```

    ## # A tibble: 6 × 13
    ##   dumpster month  year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>  <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 July   2021  2021-07-03 00:00:00        0.93                 15
    ## 2        2 July   2021  2021-07-07 00:00:00        2.26                 15
    ## 3        3 July   2021  2021-07-07 00:00:00        1.62                 15
    ## 4        4 July   2021  2021-07-16 00:00:00        1.76                 15
    ## 5        5 July   2021  2021-07-30 00:00:00        1.53                 15
    ## 6        6 August 2021  2021-08-11 00:00:00        2.06                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, source <chr>

``` r
#add a new column to identify the data source (Mr. Trash Wheel)
mr_wheel_clean <- mr_wheel_clean %>%
  mutate(source = "Mr. Trash Wheel")
head(mr_wheel_clean)
```

    ## # A tibble: 6 × 17
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## 6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ## # ℹ 11 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, ...15 <lgl>,
    ## #   ...16 <lgl>, source <chr>

``` r
#combine all datasets into one tidy dataset
combined_wheel <- bind_rows(mr_wheel_clean, prof_wheel_clean, gwynnda_wheel_clean) %>% 
  janitor::clean_names()

#look at the combined dataset
head(combined_wheel)
```

    ## # A tibble: 6 × 19
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## 6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ## # ℹ 13 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, x15 <lgl>,
    ## #   x16 <lgl>, source <chr>, plastic_bags_2 <dbl>, wrappers_2 <dbl>

The dataset combines data from three datasets: Mr. Trash Wheel,
Professor Trash Wheel, and Gwynnda Trash Wheel. There are a total of
1033 observations. Each observation represents a specific dumpster, with
key variables such as weight_tons, plastic_bottles, polystyrene, and
cigarette_butts. The total weight of trash collected by Professor Trash
Wheel is 246.74 tons. The total number of cigarette butts collected by
Gwynnda Trash Wheel in June 2022 is 1.812^{4}.

## Problem 3

``` r
#import the dataset
bakers <- read_csv("data/bakers.csv")
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes <- read_csv("data/bakes.csv")
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results <- read_csv("data/results.csv")
```

    ## New names:
    ## Rows: 1138 Columns: 5
    ## ── Column specification
    ## ──────────────────────────────────────────────────────── Delimiter: "," chr
    ## (5): ...1, ...2, ...3, ...4, IN = stayed in; OUT = Eliminated; STAR BAKE...
    ## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
    ## Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## • `` -> `...1`
    ## • `` -> `...2`
    ## • `` -> `...3`
    ## • `` -> `...4`

``` r
#look through dataset
head(bakers)
```

    ## # A tibble: 6 × 5
    ##   `Baker Name`     Series `Baker Age` `Baker Occupation` Hometown               
    ##   <chr>             <dbl>       <dbl> <chr>              <chr>                  
    ## 1 Ali Imdad             4          25 Charity worker     Saltley, Birmingham    
    ## 2 Alice Fevronia       10          28 Geography teacher  Essex                  
    ## 3 Alvin Magallanes      6          37 Nurse              Bracknell, Berkshire   
    ## 4 Amelia LeBruin       10          24 Fashion designer   Halifax                
    ## 5 Andrew Smyth          7          25 Aerospace engineer Derby / Holywood, Coun…
    ## 6 Annetha Mills         1          30 Midwife            Essex

``` r
head(bakes)
```

    ## # A tibble: 6 × 5
    ##   Series Episode Baker     `Signature Bake`                       `Show Stopper`
    ##    <dbl>   <dbl> <chr>     <chr>                                  <chr>         
    ## 1      1       1 Annetha   Light Jamaican Black Cakewith Strawbe… Red, White & …
    ## 2      1       1 David     Chocolate Orange Cake                  Black Forest …
    ## 3      1       1 Edd       Caramel Cinnamon and Banana Cake       N/A           
    ## 4      1       1 Jasminder Fresh Mango and Passion Fruit Humming… N/A           
    ## 5      1       1 Jonathan  Carrot Cake with Lime and Cream Chees… Three Tiered …
    ## 6      1       1 Lea       Cranberry and Pistachio Cakewith Oran… Raspberries a…

``` r
print(results)
```

    ## # A tibble: 1,138 × 5
    ##    ...1   ...2    ...3      ...4      IN = stayed in; OUT = Eliminated; STAR B…¹
    ##    <chr>  <chr>   <chr>     <chr>     <chr>                                     
    ##  1 <NA>   <NA>    <NA>      <NA>      <NA>                                      
    ##  2 series episode baker     technical result                                    
    ##  3 1      1       Annetha   2         IN                                        
    ##  4 1      1       David     3         IN                                        
    ##  5 1      1       Edd       1         IN                                        
    ##  6 1      1       Jasminder <NA>      IN                                        
    ##  7 1      1       Jonathan  9         IN                                        
    ##  8 1      1       Louise    <NA>      IN                                        
    ##  9 1      1       Miranda   8         IN                                        
    ## 10 1      1       Ruth      <NA>      IN                                        
    ## # ℹ 1,128 more rows
    ## # ℹ abbreviated name:
    ## #   ¹​`IN = stayed in; OUT = Eliminated; STAR BAKER = Star Baker; WINNER = Series Winner; Runner-up = Series Runner up; WD = withdrew`

``` r
#make results dataset more readable and reasonable
results <- results %>%
  slice(-2) %>%  
  rename(series = 1, episode = 2, baker = 3, technical = 4, result = 5) %>%
  filter(!is.na(series))
print(results)
```

    ## # A tibble: 1,136 × 5
    ##    series episode baker     technical result
    ##    <chr>  <chr>   <chr>     <chr>     <chr> 
    ##  1 1      1       Annetha   2         IN    
    ##  2 1      1       David     3         IN    
    ##  3 1      1       Edd       1         IN    
    ##  4 1      1       Jasminder <NA>      IN    
    ##  5 1      1       Jonathan  9         IN    
    ##  6 1      1       Louise    <NA>      IN    
    ##  7 1      1       Miranda   8         IN    
    ##  8 1      1       Ruth      <NA>      IN    
    ##  9 1      1       Lea       10        OUT   
    ## 10 1      1       Mark      <NA>      OUT   
    ## # ℹ 1,126 more rows

``` r
#extract first names from Baker Name in `bakers`, and make data more reasonable to read
bakers_clean <- bakers %>%
  separate(`Baker Name`, into = c("First Name", "Last Name"), sep = " ", extra = "merge", fill = "right") %>%
  mutate(baker = tolower(`First Name`)) %>%
  rename(series = `Series`,
         baker_age = `Baker Age`,
         baker_occupation = `Baker Occupation`,
         hometown = `Hometown`) %>% 
  select(baker, series, baker_age, baker_occupation, hometown)

print(bakers_clean)
```

    ## # A tibble: 120 × 5
    ##    baker     series baker_age baker_occupation             hometown             
    ##    <chr>      <dbl>     <dbl> <chr>                        <chr>                
    ##  1 ali            4        25 Charity worker               Saltley, Birmingham  
    ##  2 alice         10        28 Geography teacher            Essex                
    ##  3 alvin          6        37 Nurse                        Bracknell, Berkshire 
    ##  4 amelia        10        24 Fashion designer             Halifax              
    ##  5 andrew         7        25 Aerospace engineer           Derby / Holywood, Co…
    ##  6 annetha        1        30 Midwife                      Essex                
    ##  7 antony         9        30 Banker                       London               
    ##  8 beca           4        31 Military Wives' Choir Singer Aldershot, Hampshire 
    ##  9 ben            2        31 Graphic Designer             Northampton          
    ## 10 benjamina      7        23 Teaching assistant           South London         
    ## # ℹ 110 more rows

``` r
#clean `bakes` dataset
bakes_clean <- bakes %>%
  mutate(Baker = tolower(Baker),       
         Series = tolower(Series),     
         Episode = as.character(Episode)) %>%
  rename(series = `Series`, 
         episode =`Episode`,
         baker = `Baker`,
         signature_bake = `Signature Bake`,
         show_stopper = `Show Stopper`)

print(bakes_clean)
```

    ## # A tibble: 548 × 5
    ##    series episode baker     signature_bake                          show_stopper
    ##    <chr>  <chr>   <chr>     <chr>                                   <chr>       
    ##  1 1      1       annetha   "Light Jamaican Black Cakewith Strawbe… Red, White …
    ##  2 1      1       david     "Chocolate Orange Cake"                 Black Fores…
    ##  3 1      1       edd       "Caramel Cinnamon and Banana Cake"      N/A         
    ##  4 1      1       jasminder "Fresh Mango and Passion Fruit Humming… N/A         
    ##  5 1      1       jonathan  "Carrot Cake with Lime and Cream Chees… Three Tiere…
    ##  6 1      1       lea       "Cranberry and Pistachio Cakewith Oran… Raspberries…
    ##  7 1      1       louise    "Carrot and Orange Cake"                Never Fail …
    ##  8 1      1       mark      "Sticky Marmalade Tea Loaf"             Heart-shape…
    ##  9 1      1       miranda   "Triple Layered Brownie Meringue Cake\… Three Tiere…
    ## 10 1      1       ruth      "Three Tiered Lemon Drizzle Cakewith F… Classic Cho…
    ## # ℹ 538 more rows

``` r
#clean `results` dataset
results_clean <- results %>%
  mutate(baker = tolower(baker),     
         series = tolower(series),    
         episode = as.character(episode))

print(results_clean)
```

    ## # A tibble: 1,136 × 5
    ##    series episode baker     technical result
    ##    <chr>  <chr>   <chr>     <chr>     <chr> 
    ##  1 1      1       annetha   2         IN    
    ##  2 1      1       david     3         IN    
    ##  3 1      1       edd       1         IN    
    ##  4 1      1       jasminder <NA>      IN    
    ##  5 1      1       jonathan  9         IN    
    ##  6 1      1       louise    <NA>      IN    
    ##  7 1      1       miranda   8         IN    
    ##  8 1      1       ruth      <NA>      IN    
    ##  9 1      1       lea       10        OUT   
    ## 10 1      1       mark      <NA>      OUT   
    ## # ℹ 1,126 more rows

``` r
#turn series into character make sure anti_join work
bakes_clean <- bakes_clean %>%
  mutate(series = as.character(series))

bakers_clean <- bakers_clean %>%
  mutate(series = as.character(series))

#check if unmatched bakers in `bakes`
unmatched_bakes <- bakes_clean %>%
  anti_join(bakers_clean, by = c("baker", "series"))

#check if unmatched bakers for `results`
unmatched_results <- results_clean %>%
  anti_join(bakers_clean, by = c("baker", "series"))

print(unmatched_bakes)
```

    ## # A tibble: 8 × 5
    ##   series episode baker    signature_bake                            show_stopper
    ##   <chr>  <chr>   <chr>    <chr>                                     <chr>       
    ## 1 2      1       "\"jo\"" Chocolate Orange CupcakesOrange and Card… Chocolate a…
    ## 2 2      2       "\"jo\"" Caramelised Onion, Gruyere and Thyme Qui… Raspberry a…
    ## 3 2      3       "\"jo\"" Stromboli flavored with Mozzarella, Ham,… Unknown     
    ## 4 2      4       "\"jo\"" Lavender Biscuits                         Blueberry M…
    ## 5 2      5       "\"jo\"" Salmon and Asparagus Pie                  Apple and R…
    ## 6 2      6       "\"jo\"" Rum and Raisin Baked Cheesecake           Limoncello …
    ## 7 2      7       "\"jo\"" Raspberry & Strawberry Mousse Cake        Pain Aux Ra…
    ## 8 2      8       "\"jo\"" Raspberry and Blueberry Mille Feuille     Mini Victor…

``` r
print(unmatched_results)
```

    ## # A tibble: 8 × 5
    ##   series episode baker  technical result    
    ##   <chr>  <chr>   <chr>  <chr>     <chr>     
    ## 1 2      1       joanne 11        IN        
    ## 2 2      2       joanne 10        IN        
    ## 3 2      3       joanne 1         IN        
    ## 4 2      4       joanne 8         IN        
    ## 5 2      5       joanne 6         IN        
    ## 6 2      6       joanne 1         STAR BAKER
    ## 7 2      7       joanne 3         IN        
    ## 8 2      8       joanne 1         WINNER

By checking it seems there are 8 unmatched results. However, after
observation they are all from same person just that the inconsistent
name conventions, jo stands for joannes (they show up in smae series and
episode and has similar name short cut so we conlcude that).

``` r
#remove any extra quote mark in the `baker` 
bakes_clean <- bakes_clean %>%
  mutate(baker = gsub('"', '', baker)) 

bakers_clean <- bakers_clean %>%
  mutate(baker = gsub('"', '', baker))

# Correct the baker's name from Joanne to Jo
results_clean <- results_clean %>%
  mutate(baker = ifelse(series == "2" & baker == "joanne", "jo", baker))

# Do the same for bakes_clean
bakes_clean <- bakes_clean %>%
  mutate(baker = ifelse(series == "2" & baker == "joanne", "jo", baker))
```

``` r
#check if unmatched bakers in `bakes`
unmatched_bakes_2 <- bakes_clean %>%
  anti_join(bakers_clean, by = c("baker", "series"))

#check if unmatched bakers for `results`
unmatched_results_2 <- results_clean %>%
  anti_join(bakers_clean, by = c("baker", "series"))

print(unmatched_bakes_2)
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <chr>, episode <chr>, baker <chr>,
    ## #   signature_bake <chr>, show_stopper <chr>

``` r
print(unmatched_results_2)
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <chr>, episode <chr>, baker <chr>, technical <chr>,
    ## #   result <chr>

the result looks good here has no unmatched data, the datasets are
complete and correct.

``` r
#merge bakers and results on baker and series
bakers_results <- full_join(bakers_clean, results_clean, by = c("baker", "series"))

#merge bakers with bakes on baker, series, and episode
final_dataset <- full_join(bakers_results, bakes_clean, by = c("baker", "series", "episode"))

#see the final dataset
print(final_dataset)
```

    ## # A tibble: 1,136 × 10
    ##    baker series baker_age baker_occupation hometown     episode technical result
    ##    <chr> <chr>      <dbl> <chr>            <chr>        <chr>   <chr>     <chr> 
    ##  1 ali   4             25 Charity worker   Saltley, Bi… 1       11        IN    
    ##  2 ali   4             25 Charity worker   Saltley, Bi… 2       9         IN    
    ##  3 ali   4             25 Charity worker   Saltley, Bi… 3       5         IN    
    ##  4 ali   4             25 Charity worker   Saltley, Bi… 4       8         OUT   
    ##  5 ali   4             25 Charity worker   Saltley, Bi… 5       <NA>      <NA>  
    ##  6 ali   4             25 Charity worker   Saltley, Bi… 6       <NA>      <NA>  
    ##  7 ali   4             25 Charity worker   Saltley, Bi… 7       <NA>      <NA>  
    ##  8 ali   4             25 Charity worker   Saltley, Bi… 8       <NA>      <NA>  
    ##  9 ali   4             25 Charity worker   Saltley, Bi… 9       <NA>      <NA>  
    ## 10 ali   4             25 Charity worker   Saltley, Bi… 10      <NA>      <NA>  
    ## # ℹ 1,126 more rows
    ## # ℹ 2 more variables: signature_bake <chr>, show_stopper <chr>

``` r
write_csv(final_dataset, "data/final_baking_dataset.csv")
```

For data cleaning process, after loading the data i found the results
dataset look unreasonable as the column name were represented by numbers
and first row is name of the column, so I remove the first row and
change the name of the column. Next, I’ve noticed the baker in bakers
dataset is formed as First Name plus Last Name, which is completely
inconsistent to other dataset, so I change that by create a new column
that only contains baker’s first name. and I rename all the column names
to lower letters or with \_ between words and I did same procedure to
other two datasets. I next checked whether the datasets is matched or
not and found 8 unmatched row because of the inconsistent name
conventions, and I fix it by remove the conventions part and make all
name consistent. Then I retest for matches and found all rows are
matched. Lastly I merge all the dataset and write a csv final document.
The choice I make is that I opted to correct mismatched names (like jo
vs. joanne) rather than removing or excluding them, to preserve the
completeness of the data. Another one is that instead of using inner
join I use full join as inner join will dismiss series 9 and 10. The
final dataset includes all relevant details from the bakers, bakes, and
results datasets. Each row contains the baker, series, episode,
baker_age, baker_occupation, hometown, their signature bake, show
stopper, technical score, and final result for that episode.

``` r
#filter the final dataset for Seasons 5 through 10 and extract star bakers or winners
star_bakers <- final_dataset %>%
  filter(series %in% c(5, 6, 7, 8, 9, 10)) %>%
  filter(result == "STAR BAKER" | result == "WINNER") %>%
  mutate(series = as.numeric(series)) %>%  
  select(series, episode, baker, result) %>%
  arrange(series, episode)  %>%
  mutate(series = as.character(series))

#see the star baker or winner table
print(star_bakers)
```

    ## # A tibble: 60 × 4
    ##    series episode baker   result    
    ##    <chr>  <chr>   <chr>   <chr>     
    ##  1 5      1       nancy   STAR BAKER
    ##  2 5      10      nancy   WINNER    
    ##  3 5      2       richard STAR BAKER
    ##  4 5      3       luis    STAR BAKER
    ##  5 5      4       richard STAR BAKER
    ##  6 5      5       kate    STAR BAKER
    ##  7 5      6       chetna  STAR BAKER
    ##  8 5      7       richard STAR BAKER
    ##  9 5      8       richard STAR BAKER
    ## 10 5      9       richard STAR BAKER
    ## # ℹ 50 more rows

In most of the cases, the final winner was expected based on their
consistent performance throughout the season. For example: In Season 10,
Steph was named Star Baker four times, indicating strong performance,
although David ultimately became the Winner, which could be considered a
bit of a surprise. In Season 9, Rahul was a dominant figure, being
awarded Star Baker three times before winning the season. His consistent
success made him a predictable winner. In Season 6, Nadiya’s victory was
anticipated, as she was named Star Baker three times before winning.
Again season 10 seems a bit surprise as Steph win Star Baker four times
but lose the final title to David. Season 5 is also very suprised as
Richard is season 5 claim Star Baker five times almost dominant the
whole season, but Nancy won the final.

``` r
#import the viewer data
viewers <- read_csv("data/viewers.csv")
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#clean and tidy the viewer data
viewers_clean <- viewers %>%
  janitor::clean_names()
```

``` r
#show the first 10 rows of the cleaned viewer dataset
print(head(viewers_clean, 10))
```

    ## # A tibble: 10 × 11
    ##    episode series_1 series_2 series_3 series_4 series_5 series_6 series_7
    ##      <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>
    ##  1       1     2.24     3.1      3.85     6.6      8.51     11.6     13.6
    ##  2       2     3        3.53     4.6      6.65     8.79     11.6     13.4
    ##  3       3     3        3.82     4.53     7.17     9.28     12.0     13.0
    ##  4       4     2.6      3.6      4.71     6.82    10.2      12.4     13.3
    ##  5       5     3.03     3.83     4.61     6.95     9.95     12.4     13.1
    ##  6       6     2.75     4.25     4.82     7.32    10.1      12       13.1
    ##  7       7    NA        4.42     5.1      7.76    10.3      12.4     13.4
    ##  8       8    NA        5.06     5.35     7.41     9.02     11.1     13.3
    ##  9       9    NA       NA        5.7      7.41    10.7      12.6     13.4
    ## 10      10    NA       NA        6.74     9.45    13.5      15.0     15.9
    ## # ℹ 3 more variables: series_8 <dbl>, series_9 <dbl>, series_10 <dbl>

``` r
#the average viewer for Season 1
avg_s1 <- viewers_clean %>%
  summarise(avg = mean(series_1, na.rm = TRUE))

#the average viewer for Season 5
avg_s5 <- viewers_clean %>%
  summarise(avg = mean(series_5, na.rm = TRUE))

#look at the average viewer for Season 1 and Season 5
print(avg_s1$avg)
```

    ## [1] 2.77

``` r
print(avg_s5$avg)
```

    ## [1] 10.0393

the average viewership in Season 1 is 2.77 and 10.0393 for season 5.
